# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Github-Trending

on:
  schedule:
    - cron: "30 23 * * *"
    - cron: "30 23 * * 6"
    # - cron: "*/2 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scraper
      if: github.event.schedule == '30 23 * * *'
      run: |
        python scraper_github_rending.py

    - name: Run Scraper week
      if: github.event.schedule == '30 23 * * 6'
      run: |
        python scraper_github_rending_week.py

    # Runs a set of commands using the runners shell
    - name: push to origin master
      run: |
        echo start push
        git config --global user.name "Cao Yanfei"
        git config --global user.email "github@uyhnm.cn"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
